### ISSUE TITLE
Release with CoreDNS 1.9.3

### ISSUE THREAD

**Issue by mrbluecoat** [relekang/coredns-blocklist#1]
Cool project! Your CoreDNS 1.8.1 is fairly outdated now; mind compiling with CoreDNS 1.9.3? https://github.com/coredns/coredns/releases

**Comment by relekang** [comment]
Thanks, it should be up now: https://github.com/relekang/coredns-blocklist/releases/tag/v1.6.1

Also created dependabot settings to update once a day should help against going out of date since I don't often check this repo since my dns servers is not tought much of as long as they are working 😅
